language: cpp
services:
  - docker
sudo: required
compiler:
- gcc
before_install:
- docker pull matrim/cmake-examples:3.4.3
script:
- docker run --rm -v $PWD:/data/code -it matrim/cmake-examples:3.4.3 /data/code/test.sh
branches:
  except:
  - gh-pages
notifications:
  email: true
os:
- linux
