language: cpp
sudo: required
compiler:
- gcc
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y cmake libboost-all-dev libprotobuf-dev protobuf-compiler cppcheck; fi
script:
- ./test.sh
branches:
  only:
  - master
notifications:
  email: true
os:
- linux
